name: Publish release

on:
  release:
    types: [published]
permissions: read-all
jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Publish artifact
        run: |
          ./gradlew publish

